"use client";

import { Amplify } from "aws-amplify";
import outputs from "@/amplify_outputs.json";

// This loads the configuration from the file generated by the sandbox
Amplify.configure(outputs);

export default function ConfigureAmplifyClientSide() {
  return null;
}