import type { Metadata } from "next";
import { Geist, Geist_Mono, Merriweather, Tangerine } from "next/font/google";
import ConfigureAmplifyClientSide from "./components/ConfigureAmplifyClientSide/ConfigureAmplifyClientSide";
import '@aws-amplify/ui-react/styles.css';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const merriweather = Merriweather({
  subsets: ["latin"],
  weight: "400",
});

const tangerine = Tangerine({
   subsets: ["latin"],                                                                   
   weight: "400",
   variable: "--font-tangerine",
})

const currentEnv = process.env.NEXT_PUBLIC_ENV;
const isDevEnv = currentEnv === "dev";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
    icons: {
        icon: "/images/marco-valeri-net-logo.jpg"
    },
    robots: {
        index: !isDevEnv,
        follow: !isDevEnv,
    }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${merriweather.className} ${tangerine.variable} antialiased`}
      >
        <ConfigureAmplifyClientSide />
        {children}
      </body>
    </html>
  );
}
