import type { Metadata } from "next";
import { Geist, Geist_Mono, Merriweather, Tangerine } from "next/font/google";
import ConfigureAmplify from "./components/ConfigureAmplify/ConfigureAmplify";
import Providers from "./providers";
import '@aws-amplify/ui-react/styles.css';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const merriweather = Merriweather({
  subsets: ["latin"],
  weight: "400",
});

const tangerine = Tangerine({
   subsets: ["latin"],                                                                   
   weight: "400",
   variable: "--font-tangerine",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${merriweather.className} ${tangerine.variable} antialiased`}
      >
        <ConfigureAmplify />
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
